# Generated by Django 5.2.4 on 2025-09-28 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_dob', models.DateField()),
                ('status', models.CharField(choices=[('SENT_CLINIC', 'Sent from Clinic'), ('RECEIVED_BY_LAB', 'Received by Lab'), ('RETURNED_BY_LAB', 'Returned by Lab'), ('RECEIVED_BY_CLINIC', 'Received by Clinic')], default='SENT_CLINIC', max_length=20)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('protection_code', models.CharField(editable=False, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT_CLINIC', 'Sent from Clinic'), ('RECEIVED_BY_LAB', 'Received by Lab'), ('RETURNED_BY_LAB', 'Returned by Lab'), ('RECEIVED_BY_CLINIC', 'Received by Clinic')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('actor', models.CharField(choices=[('CLINIC', 'Clinic'), ('LAB', 'Lab'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=12)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.case')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
