# Generated by Django 5.2.4 on 2025-09-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.lab'),
        ),
        migrations.AlterField(
            model_name='case',
            name='protection_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
    ]
