# Generated by Django 5.2.4 on 2025-09-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_lab_pin_hash_userprofile_lab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='pin_hash',
            new_name='praxis_pin_hash',
        ),
    ]
