# Generated by Django 5.2.4 on 2025-10-07 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_pin_hash_appsettings_praxis_pin_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='returned_tracking_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='substage',
            field=models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('MILL', 'Fräsen'), ('SINTER', 'Sintern'), ('GLAZE', 'Glasur'), ('QA', 'Qualitätsprüfung')], max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='action',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('SENT_CLINIC', 'Von Praxis gesendet'), ('RECEIVED_BY_LAB', 'Im Labor eingegangen'), ('RETURNED_BY_LAB', 'An Praxis zurückgesendet'), ('RECEIVED_BY_CLINIC', 'In Praxis erhalten')], default='SENT_CLINIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('SENT_CLINIC', 'Von Praxis gesendet'), ('RECEIVED_BY_LAB', 'Im Labor eingegangen'), ('RETURNED_BY_LAB', 'An Praxis zurückgesendet'), ('RECEIVED_BY_CLINIC', 'In Praxis erhalten')], max_length=20),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_attachments/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tracker.case')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
